name: Proselint

on:
  push:
    branches:
      - main

jobs:
  proselint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install proselint
      run: |
        sudo apt-get update && sudo apt-get install -y proselint

    - name: Run proselint
      run: |
        find . -name "*.md" -exec proselint {} +